### ISSUE TITLE
Link update under training

### ISSUE THREAD

**Issue by riyazwalikar** [magnologan/awesome-k8s-security#11]
Hi, 

The link for "Attacking and Auditing Docker Containers and Kubernetes Clusters" is broken under https://github.com/magnologan/awesome-k8s-security#trainings.

Here's the correct working link - https://github.com/Kloudle/attacking-and-auditing-docker-containers-and-kubernetes-clusters-training

Thank you.

**Comment by magnologan** [comment]
Updated. Thanks for flagging! Cheers!
